#!/usr/bin/env node
/**
 * Project Update Logger
 * Creates and maintains summary logs for each batch of updates
 */

const fs = require('fs');
const path = require('path');

const LOG_DIR = '/home/desktop/clawd/logs/project-updates';

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

function getTimestamp() {
  const now = new Date();
  return {
    date: now.toISOString().split('T')[0],
    time: now.toTimeString().split(' ')[0],
    datetime: now.toISOString()
  };
}

// Create or append to project update log
function logProjectUpdate(projectName, updates) {
  ensureDir(LOG_DIR);
  
  const ts = getTimestamp();
  const logFile = path.join(LOG_DIR, `${projectName.toLowerCase().replace(/\s+/g, '-')}-updates.md`);
  
  // Read existing log
  let existingContent = '';
  if (fs.existsSync(logFile)) {
    existingContent = fs.readFileSync(logFile, 'utf-8');
  }
  
  // Create new entry
  const newEntry = `## Update: ${ts.date} ${ts.time}\n\n` +
    `**Batch:** ${updates.batch || 'General Update'}\n\n` +
    `### Completed ✅\n` +
    (updates.completed?.map(i => `- ✅ ${i}`).join('\n') || '- _No items_') +
    `\n\n` +
    `### In Progress 🔄\n` +
    (updates.inProgress?.map(i => `- 🔄 ${i}`).join('\n') || '- _No items_') +
    `\n\n` +
    `### Next Steps 📋\n` +
    (updates.nextSteps?.map(i => `- [ ] ${i}`).join('\n') || '- _No items_') +
    `\n\n` +
    `### Notes 💡\n` +
    (updates.notes || '_No notes_') +
    `\n\n---\n\n`;
  
  // Prepend new entry to existing content
  const header = existingContent.includes('# Project Update Log') 
    ? '' 
    : `# ${projectName} - Update Log\n\n` +
      `**Project:** ${projectName}  \n` +
      `**Created:** ${ts.date}  \n` +
      `**Status:** Active  \n\n` +
      `---\n\n`;
  
  const fullContent = header + newEntry + existingContent.replace(`# ${projectName} - Update Log\n\n`, '');
  
  fs.writeFileSync(logFile, fullContent);
  
  console.log(`✅ Updated log: ${logFile}`);
  return logFile;
}

// Generate summary for ClickUp comment
function generateUpdateSummary(projectName, updates) {
  const ts = getTimestamp();
  
  return `## 📋 Update Summary - ${ts.date}\n\n` +
    `**Project:** ${projectName}\n` +
    `**Batch:** ${updates.batch || 'Development Update'}\n\n` +
    `### ✅ Completed (${updates.completed?.length || 0})\n` +
    (updates.completed?.map(i => `- ${i}`).join('\n') || '_No completed items_') +
    `\n\n` +
    `### 🔄 In Progress (${updates.inProgress?.length || 0})\n` +
    (updates.inProgress?.map(i => `- ${i}`).join('\n') || '_No in-progress items_') +
    `\n\n` +
    `### 📋 Next Steps (${updates.nextSteps?.length || 0})\n` +
    (updates.nextSteps?.map(i => `- [ ] ${i}`).join('\n') || '_No next steps_') +
    `\n\n` +
    `---\n` +
    `_Auto-generated by Clawd_ 🦎`;
}

// CLI
const args = process.argv.slice(2);
const command = args[0];

if (command === 'log') {
  const project = args[1];
  if (!project) {
    console.error('Usage: project-logger.js log <project-name>');
    process.exit(1);
  }
  
  // Example batch (would come from actual work tracking)
  const updates = {
    batch: 'Initial Setup',
    completed: ['Created project structure', 'Set up ClickUp folder', 'Added task lists'],
    inProgress: ['Sync configuration', 'Documentation'],
    nextSteps: ['Create GitHub repo', 'Add initial code', 'Test integration'],
    notes: 'Project initialized and ready for development'
  };
  
  const logFile = logProjectUpdate(project, updates);
  const summary = generateUpdateSummary(project, updates);
  
  console.log('\n=== Update Summary for ClickUp ===\n');
  console.log(summary);
  
} else if (command === 'show') {
  const project = args[1];
  if (!project) {
    console.error('Usage: project-logger.js show <project-name>');
    process.exit(1);
  }
  
  const logFile = path.join(LOG_DIR, `${project.toLowerCase().replace(/\s+/g, '-')}-updates.md`);
  if (fs.existsSync(logFile)) {
    console.log(fs.readFileSync(logFile, 'utf-8'));
  } else {
    console.log(`No update log found for ${project}`);
  }
  
} else {
  console.log(`
Project Update Logger

Usage:
  project-logger.js log <project-name>   Log a new update batch
  project-logger.js show <project-name>  Show update history

Examples:
  project-logger.js log "Ops Center"
  project-logger.js show "Tour Website"
`);
}
